name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: juice
          MYSQL_PASSWORD: juice
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -P 3306"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    
    - name: Install dependencies
      run: go mod download

    - name: Wait for MySQL
      run: |
        timeout 30s bash -c 'until mysql -h 127.0.0.1 -P 3306 -u juice -pjuice -e "SELECT 1"; do sleep 1; done'
      
    - name: Run benchmarks
      run: |
        # 显示工作目录内容
        ls -la
        
        # 显示环境变量
        echo "DATA_SOURCE: $DATA_SOURCE"
        
        # 运行测试并显示详细输出
        go test -v -bench=. -benchmem ./... 2>&1 | tee benchmark_results.txt
      env:
        DATA_SOURCE: juice:juice@tcp(127.0.0.1:3306)/test?parseTime=true

    - name: Store benchmark result
      if: success()
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Go Benchmark
        tool: 'go'
        output-file-path: benchmark_results.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: true
        gh-pages-branch: gh-pages
        benchmark-data-dir-path: dev/bench
        comment-always: true
        skip-fetch-gh-pages: true
        max-items-in-chart: 100
