name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: juice
          MYSQL_PASSWORD: juice
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -P 3306"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout benchmark repository
        uses: actions/checkout@v3
        with:
          path: juice-benchmark

      - name: Checkout juice repository
        uses: actions/checkout@v3
        with:
          repository: go-juicedev/juice
          path: juice

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Install dependencies
        run: |
          cd juice-benchmark
          go mod tidy

      - name: Wait for MySQL
        run: |
          timeout 30s bash -c 'until mysql -h 127.0.0.1 -P 3306 -u juice -pjuice -e "SELECT 1"; do sleep 1; done'

      - name: Run benchmarks
        run: |
          cd juice-benchmark
          # 显示工作目录内容
          ls -la
          
          # 显示环境变量
          echo "DATA_SOURCE: $DATA_SOURCE"
          
          # 运行测试并显示详细输出
          go test -v -bench=. -benchmem ./... 2>&1 | tee benchmark_results.txt
        env:
          DATA_SOURCE: juice:juice@tcp(127.0.0.1:3306)/test?parseTime=true