name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 允许手动触发
  workflow_dispatch:

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: juice
          MYSQL_PASSWORD: juice
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    
    - name: Install dependencies
      run: go mod download

    - name: Run benchmarks
      run: |
        go test -bench=. -benchmem | tee benchmark_results.txt
      env:
        DATA_SOURCE: juice:juice@tcp(localhost:3306)/test?parseTime=true

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Go Benchmark
        tool: 'go'
        output-file-path: benchmark_results.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        # 在 main 分支上保存基准测试结果
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: true
        # 可选：将结果发布到 GitHub Pages
        gh-pages-branch: gh-pages
        benchmark-data-dir-path: dev/bench
